// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts"
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Ela se refere a uma URL de conexão de banco de dados separada e temporária que é usada exclusivamente para gerenciar as alterações (migrações) no esquema do seu banco de dados principal.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
